# Generated by Django 3.2.16 on 2022-12-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='DOB',
        ),
        migrations.AddField(
            model_name='person',
            name='geeks_field',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
