# Generated by Django 3.2.16 on 2022-12-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_rename_geeks_field_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='DOB',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth(mm-dd-yy)'),
        ),
    ]
