# Generated by Django 3.2.16 on 2022-12-19 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20221219_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of birth(yy-mm-dd)'),
            preserve_default=False,
        ),
    ]
