# Generated by Django 3.2.16 on 2022-12-19 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_alter_person_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Gender',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='M/F/O'),
            preserve_default=False,
        ),
    ]
